### ISSUE TITLE
Problem While Cloning Repository

### ISSUE THREAD

**Issue by Muhammad-Daniyal-Jawad1** [saleha-muzammil/Academic-Time-Machine#1]
I seem to have some difficulty in cloning this repository. It is giving me this error as shown in the screenshot below. If anyone can help in resolving this issue, I would be grateful. The screenshot is attached below.

<img width="417" alt="image" src="https://github.com/saleha-muzammil/Academic-Time-Machine/assets/130592856/3e7bcf98-b090-4156-b885-98ab33470c4b">

**Comment by saleha-muzammil** [comment]
There were two paths for sda/2022 , ig that might be the reason it was giving the error. Erased the spare directory, try again now.

**Comment by Muhammad-Daniyal-Jawad1** [comment]
I did try to clone this two times again, and this error occurred.

<img width="442" alt="image" src="https://github.com/saleha-muzammil/Academic-Time-Machine/assets/130592856/429180bd-189e-4aa5-9aba-958f84fc4a65">

**Comment by siftullah** [comment]
fixed it...can clone successfully now

**Comment by saleha-muzammil** [comment]
Perfectt
