### ISSUE TITLE
Data st

### ISSUE THREAD

**Issue by junaidzeb123** [saleha-muzammil/Academic-Time-Machine#18]
[Question 2 and 3 Solution.pdf](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726355/Question.2.and.3.Solution.pdf)
[data final.pdf](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726356/data.final.pdf)
[Question 4, 5 and 6 Solution.pdf](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726357/Question.4.5.and.6.Solution.pdf)
[Solution DataStructure_Final_Exam_Bilal Khalid Dar.pdf](https://github.com/saleha-muzammil/Academic-Time
[DS-2020_Final.pdf](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726366/DS-2020_Final.pdf)
[DS-2016_Final_Sol.pdf](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726368/DS-2016_Final_Sol.pdf)
[Data Structures_Sessional-I_2017.pdf](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726369/Data.Structures_Sessional-I_2017.pdf)
[CS218 Data Structures Mid-1.docx](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726371/CS218.Data.Structures.Mid-1.docx)
[CS218 Data Structures Mid-1 Solution.docx](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726373/CS218.Data.Structures.Mid-1.Solution.docx)
[Data Sessional 2 Sol.pdf](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726374/Data.Sessional.2.Sol.pdf)
-Machine/files/13726360/Solution.DataStructure_Final_Exam_Bilal.Khalid.Dar.pdf)
[Data Structures_Mid_Fall-2018 (2).pdf](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726376/Data.Structures_Mid_Fall-2018.2.pdf)
t
[Data Structures_Mid_Fall-2018 (1).pdf](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726377/Data.Structures_Mid_Fall-2018.1.pdf)
ructue 
[DS Final Fall 2022- Solution (1).pdf](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726378/DS.Final.Fall.2022-.Solution.1.pdf)
ma
[DS Spring 23 Part 2 Solution_230807_110622.pdf](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726379/DS.Spring.23.Part.2.Solution_230807_110622.pdf)
terail
[DS Final Fall 2022- Solution.pdf](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726380/DS.Final.Fall.2022-.Solution.pdf)
[DS_Mid_Fall-2018_Soln.pdf](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726381/DS_Mid_Fall-2018_Soln.pdf)
[DS mid 1 solution.docx](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726382/DS.mid.1.solution.docx)
[DS mid 1.docx](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726383/DS.mid.1.docx)
rut
[Data Structures_Mid_Fall-2018.pdf](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726384/Data.Structures_Mid_Fall-2018.pdf)
ue mat
[Data Structures_Sessional-1_2015.pdf](https://github.com/saleha-muzammil/Academic-Time-Machine/files/13726385/Data.Structures_Sessional-1_2015.pdf)
ereail

**Comment by junaidzeb123** [comment]
some data structure past paper islamabad campus

**Comment by saleha-muzammil** [comment]
We will have to create a separate branch for Islamabad

**Comment by saleha-muzammil** [comment]
Created islamabad branch, kindly send merge requests for that specific branch
