### ISSUE TITLE
Create Islamabad Branch

### ISSUE THREAD

**Issue by blueork** [saleha-muzammil/Academic-Time-Machine#19]
It is requested, as per the discussion previously had, to create a separate branch for Islamabad Campus. Also, as content is added to the Islamabad Branch, should the content related to the Lahore Campus be removed from it or not?

**Comment by saleha-muzammil** [comment]
Done, kindly fork, add relevant material to it and send merge requests for the Islamabad  branch. i believe it would be better if it is Islamabad only
